### ISSUE TITLE
result always median

### ISSUE THREAD

**Issue by skyteks** [arnecls/ga_func_server#1]
Ich bekomme bei allen Netzwerkanfragen immer nur das Ergebnis für 'Median' zurück.
[main.cpp.txt](https://github.com/arnecls/ga_func_server/files/644173/main.cpp.txt)
Woran könnte das liegen?
`
Immediate:
Sum: 0.054682
Avg: 0.000547
Med: 0.000540
Network:
Sum: 0.000540
Avg: 0.000540
Med: 0.000540
CPU: 0.000540
MEM: 0.000540
`

**Comment by arnecls** [comment]
Weil du in Zeile 134 auch immer nur den Median anfragst.
```
auto req = CreateRequest(median, count, pData);
```
Sollte sein
```
auto req = CreateRequest(type, count, pData);
```
